### ISSUE TITLE
skeleton contains git config templates

### ISSUE THREAD

**Issue by vinzv** [siduction/settings-kde#1]
There are files in [/etc/skel/.config/](https://github.com/siduction/settings-kde/tree/farewell/etc/skel/config) which I would not expect, especially their contents.

_gitconfig_
(which is okay, somewhat)

_gitignore_
```
.ICEauthority
.Xauthority
.bash_history
.cache/
.config/chromium/
.config/pulse/
.dbus/
.gconf/
.gnupg/
.pki/
.xfce4-session.*
.xsession-errors
```

Is this on purpose?

**Comment by fethomm** [comment]
I guess they are on purpose, but to what avail, only agaida could answer. My /etc/skel/.config in one of my installs contains:
kactivitymanagerdrc  
plank  
plasma-org.kde.plasma.desktop-appletsrc

Both plasma-related packages are part of kde-settings. Why plank is in there, I have no idea.
